#!/bin/sh
echo "Install Redis"
sudo yum install redis
sudo systemctl enable redis
sudo systemctl start redis


echo "Install yarn"
npm install --global yarn




echo "Install pm2"
npm install pm2 -g


echo "Install mariadb"
curl -LsS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | sudo bash -s -- --mariadb-server-version=11.4
sudo dnf -qy module disable mariadb
sudo dnf module reset mariadb -y
sudo dnf install MariaDB-server MariaDB-client
systemctl start mariadb
systemctl status mariadb
systemctl enable mariadb


# secure the instance
sudo mariadb-secure-installation
